# Generated by Django 4.0.1 on 2022-01-08 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('correct_answer', models.IntegerField()),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('number_of_points', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'question_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=25, unique=True)),
                ('subject_details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('final_grade', models.IntegerField()),
            ],
            options={
                'db_table': 'submission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submittedanswer',
            fields=[
                ('submitted_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_answer_open_question', models.TextField(blank=True, null=True)),
                ('assigned_grade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submittedanswer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('teacher_subject_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teacher_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=45, unique=True)),
                ('test_password', models.CharField(blank=True, max_length=128, null=True)),
                ('test_date', models.DateField()),
                ('test_start_time', models.TimeField()),
                ('test_end_time', models.TimeField()),
                ('max_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='questions.user')),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='questions.user')),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
